@startuml
ditaa
+--------+   +-------+    +-------+
|        +-->+ ditaa +--> |       |
|  Text  |   +-------+    |你好     |
|Document|   |!magic!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
    :                         ^
    |       Lots of work      |
    +-------------------------+
@enduml